apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: roboshop
  labels: 
    app: mongodb
    tier: db
    project: roboshop
spec:
  selector:
    matchLabels:
      app: mongodb
      tier: db
      project: roboshop
  serviceName: "mongodb"
  replicas: 1 # by default is 1
  template:
    metadata:
      labels:
        app: mongodb
        tier: db
        project: roboshop # has to match .spec.selector.matchLabels
    spec:
      containers:
      - name: mongodb
        image: "nishaldevops/mongodb:{{ .Values.statefulset.imageVersion }}"
        volumeMounts:
        - name: mongodb
          mountPath: /data/db
  # this PVC we are writing separately 
      volumes: 
      - name: mongodb
        persistentVolumeClaim: # this is the PVC
          claimName: ebs-dynamic-pvc 


